<?php

namespace AppBundle\Repository;

/**
 * ChoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoirRepository extends \Doctrine\ORM\EntityRepository
{
}
