<?php

namespace AppBundle\Repository;

/**
 * ChoristerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoristerRepository extends \Doctrine\ORM\EntityRepository
{
}
